version: '3'

services:
  cashcompadre-front:
    build: ./frontend
    depends_on:
      - cashcompadre-back
    ports:
      - 8100:80
  cashcompadre-back:
    build: ./backend
    depends_on:
      - db-cashcompadre
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-cashcompadre:3306/ccdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect    
    ports:
      - 8080:8080
  db-cashcompadre:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=ccdb
